version: "3"
services:
  sleepy_sidecar:
    build: ${PWD}
    image: sleepy_sidecar
    container_name: sleepy_sidecar
    network_mode: "host"        
    restart: unless-stopped
    command: -address 0.0.0.0 -port 10000
    volumes:
      - $PWD/src/sidecar.conf:/sidecar.conf


