version: '3'
services:
  wake_proxy:
    build: ${PWD}
    image: wake_proxy
    container_name: wake_proxy
    volumes:
      - ${PWD}/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ${PWD}/html:/usr/share/nginx/html:ro
      - ${PWD}/lua:/lua:ro
      - ${PWD}/lua-resty-http/lib:/usr/local/openresty/site/lualib
    ports:
      # wake proxy itself (for reverse proxies)
      - 80:80
      # uncomment for ssl
     # - 443:443
      # add stream services here (defined in nginx.conf)
      - 2222:2222
    restart: unless-stopped
    mem_limit: 32m
    cpus: 0.1
